theme: jekyll-theme-minimal
logo: ./logo.png
title: [Trabajo final Periodismo de Datos]
description: [En este repositorio se puede ver mi paso por la asignatura de Periodismo de Datos en el año 2022.]
